### ISSUE TITLE
Remove object from memory once sent?

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers-memory#30]
HI

  I need to have a message service for non persistent messages (to do some webrtc signaling). I think that feather-memory is what I need but how does this service implement garbadge collection. I mean do I need to call some specific function to remove a message from memory once sent to its receivers? or would this service handle it automatically?
Because my feathersjs app is meant to run for months (or years) so the memory would quickly be full if expired messages are kept into memory.

**Comment by daffl** [comment]
It is literally just a memory storage service. Removing entries through the `.remove` service method is up to you. Once removed they will be `delete`d from the store. If nothing else is referencing the deleted objects they will be garbage collected like any other JavaScript object.

**Comment by ramsestom** [comment]
Ok. So if I want to delete a message once received I just have the target client to call the .remove service once he receive it I guess.
Now is there a simple way to delete message that have never been received (because the receiver wasn't connect to the server when this message was created)?  Maybe with a timer task that regularly delete old messages on the server. But wouldn' be ideal...  

Or better, is it possible to have a feathers service with only a .create service method (find, get, update, patch, remove beeing dissabled) that directly pass some message from one client to another (based on a 'target' client ID in the message) without storing it at all (nor in a DB neither in memory). A bit like you can do with socket.io rooms where you can simply emit to all participants of a room a message sent to this room ?

**Comment by daffl** [comment]
What you want to do is what [services are for](http://docs.feathersjs.com/services/readme.html). You don't need to use the pre-done database services. A pass-through service that just provides a `create` and send the `created` event just looks like this:

```
app.use('/messages', {
  create(data) {
  }
});

**Comment by ramsestom** [comment]
With filters, the filter would be run for every connected client (which would unnecessarily consume ressources if I have a lot of connected clients/messages to filter).

So, is there any way to directly tell feathers to only send the 'created' event to a specified socket connection (having a hash table of client _id -> connection and only emit the 'created' event on the connection matching data.to_id)? 
Something like (with pure socket.io):
```
var io = require('socket.io')(server);
io.on('connection', function(socket){
socket.on('message', function(data){
    var to = io.sockets.connected[data.to_id];
    to.emit('message', data);
  });
});
```
but inside the feather service create method?

**Comment by daffl** [comment]
Do you have an example setup that causes any actual problems? Usually one instance can handle ~10k connections. Running a simple filter callback that just does a comparison (like `connection.user._id === message.to_user_id`) 10k times on a decent server takes maybe a few ms, much less than any database call.

There is definitely optimizations that can be made which I'd like to look into when refactoring the event handling into a hook (instead of a mixin) but so far I don't know of any cases where the event filtering was the actual bottleneck (as long as you don't make any DB requests or other longer running asynchronous operations every time in a filter).

**Comment by ramsestom** [comment]
I have no example setup with this issue yet but I have start to develop a chat app that would potentially have 100k to 1M concurrent users. With socket.io and eventually a small server cluster, it has been reported to be possible to handle this number of concurrent users (so I expect to be able to do the same with feathers and not restrict to ~10K connections ;) )
In my app, the majority of events are 1 to 1 (or 1 to 2-3) events (and some did not request any db call (just events to be passed from one client to another) so the db calls might not be the bottleneck for my server, could be the number of events/second). 
So pretty much all my events need to be filtered. A simple comparison may take only a few ms but multiplied by the number of users and events/second, it starts to be significant when your app grows. So I try to anticipate (if ever my app is successful and have a lot of users, it would be to late to change the server logic when it starts to be popular) and already code my app and server to be able to handle a large number of users/events (in case of). I might be doing unnecessary work here but anyway, it is never a bad idea to try to increase the efficiency of your server (event if it is only a few ms/request ;) ).
