### ISSUE TITLE
[RFE] An option to set the type of the id field to String

### ISSUE THREAD

**Issue by green-coder** [feathersjs/feathers-memory#54]
I would like to request to add an option in the service creation to have the id field be a String instead of an integer.

1. This would help users interfacing with queries which expect to compare with String IDs (e.g. like GraphQL).
2. It would allow a painless switch with the other database containers which may us Strings for their IDs.

I believe that the constructor and https://github.com/feathersjs/feathers-memory/blob/master/src/index.js#L77 would need to be modified to optionally cast the id variable from an int to a String.

**Comment by daffl** [comment]
If you set the `id` property on a `create`, that id will be used. For example to create [uuids](https://www.npmjs.com/package/uuid):

```js
const uuid = require('uuid/v4');

app.service('memoryservice').hooks({
  before: {
    create(hook) {
      const idField = hook.service.id; // service id field

      hook.data[idField] = uuid().
    }
  }
});
```

The incremented id is just a fallback for if you don't provide your own id mechanism.

**Comment by green-coder** [comment]
Yes, I am aware of that behavior. My request is to modify the fallback, as I believe that in most of the cases the user does not want to provide the id himself.

**Comment by green-coder** [comment]
Your approach should be good enough. Thank you.

**Comment by acontreras89** [comment]
It would be nice to have this example included in the `README` :)

If anyone wants to keep using `startId` and auto incremented ids:
```js
const incrementStr = hook => {
  hook.data[hook.service.id] = String(hook.service._uId++)
}
```
